### ISSUE TITLE
Figure is stretched to window size

### ISSUE THREAD

**Issue by thomasaarholt** [matplotlib/jupyter-matplotlib#117]
Jupyterlab 1.0 and ipympl 0.3.1
Regardless of what figsize is set to, the plot appears stretched, see screenshot.
![image](https://user-images.githubusercontent.com/2721423/60687228-8fc39080-9ead-11e9-8dda-3ed64b4f7426.png)

Temporary workaround:
If you want the "traditional" fixed size figure, you can use the following `figure()` function instead of `plt.figure()`:
https://gist.github.com/thomasaarholt/9841ce2424bc40e3165142764e960150

**Comment by SylvainCorlay** [comment]
Thanks @thomasaarholt this is actually the expected behavior.

The canvas size is set through the widget layout.



import matplotlib.pyplot as plt
import numpy as np

```
fig = plt.figure()
plt.plot(np.sin(np.linspace(0, 20, 100)))
fig.canvas.layout.width = '500px'
fig.canvas
```

**Comment by SylvainCorlay** [comment]
The frontend makes a request to the backend for the canvas size that is required. You can set the figure width and height in pixels, or percents.

You can also set more sophisticated layout properties. Check out the Jupyter widgets documentation here:

https://ipywidgets.readthedocs.io/en/stable/examples/Widget%20Styling.html

**Comment by martinRenou** [comment]
Maybe we could have a special case when the user provides a `figsize`?

**Comment by SylvainCorlay** [comment]
In ipympl, the canvas is a jupyter widget and layout of jupyter widget is set with the `layout` property which gives the full flexibility of CSS (including reactive layouts and flexboxes). Then the frontent makes a requests for the corresponding image size.

> And this should definitely be in the readme

PR welcome!

**Comment by tacaswell** [comment]
What happens if the widget is displayed in two places that disagree about how big it should be?  As we are pulling the png from the backend side, there is only one underlying size...

@thomasaarholt This behavior is mostly consistent, as if you resize the GUI window it re-sizes the figure behind the scenes for you (and conversely if you set the size of the figure it resizes the window).

@SylvainCorlay is it possible to affect the layout from the python side, that is probably what `Manger.resize()` should do so `fig.set_size_inches` works as expected.

**Comment by martinRenou** [comment]
> What happens if the widget is displayed in two places that disagree about how big it should be? As we are pulling the png from the backend side, there is only one underlying size..

I exactly thought about this use case this afternoon. This won't work currently.

**Comment by yoichi-kazama** [comment]
I usually use both the `inline` mode and `widget` mode, but now they have different ways to layout plots.

Here are my humble thoughts:

1. A figure as a canvas widget gives more layout flexibility. On the other hand, many users have used `figsize` to layout plots in the `widget` mode, so it would be nice if ipympl sets a canvas size automatically if `figsize` is set.

2.  If ipympl can keep plot views and status even after kernel shutdown, I wouldn't need to stick to the `inline` mode any longer.

**Comment by SylvainCorlay** [comment]
I have an idea to reconcile both approaches nicely and should also resolve
the issue of multiple views with different layouts.

Will detail this later. Going AFK for the evening.

**Comment by efiring** [comment]
Maybe the point is already clear, but in case it isn't: If ipympl is to replace the present notebook backend, then I think it should follow the latter's behavior by default in respecting the figsize set in matplotlib, regardless of whether it has been left as the mpl default or explicitly set by user code.

**Comment by tacaswell** [comment]
```
fig.canvas.layout.width = '7in'
fig.canvas.layout.height= '5in'
```

That seems to do the right thing, we just need to sort out how to thread it though for `fig.set_size_inches`....

**Comment by PhysMa** [comment]
Another change is that now the "Stop Interaction" button and the resizing handle are gone, as seen in the screenshot above and below. This caused lots of trouble for me because I rely on the button to stop live plots by matplotlib animations. Is this intended? Can we get the button back somehow?

![JLab_ipympl](https://user-images.githubusercontent.com/5281395/61998012-62a67000-b05e-11e9-8cbe-f29f96b262c1.PNG)

**Comment by thomasaarholt** [comment]
@PhysMa Would you mind creating an additional issue for that problem?

**Comment by djhoese** [comment]
Is there a way to set a global default layout size for all future figures? Kind of like the rcParams? That way a user could set the preferred width at the top of a notebook and have it set for the remainder of the notebook.

**Comment by Raudcu** [comment]
One of the main disavantage I see with this new way of displaying is that several times I use the interactive mode together with plt.savefig to get pdf's of the plots: before, I kind of had a "what you see is what you get" but now that's gone.

**Comment by djhoese** [comment]
I've never really used the `widget` display before this week while setting up lessons for a class. The main UX issue I'm running in to is that when using `imshow` my default browser width, along with the default height of the cell, almost never represent the aspect ratio of the data I'm showing with my `imshow` calls. Since I'm looking at satellite imagery this can cause the images to look extremely distorted.

![image](https://user-images.githubusercontent.com/1828519/62071236-b604f380-b201-11e9-8a34-b4c78e326901.png)

I'm guessing that setting the default size based on the `imshow` array would be just as hard if not harder than what @tacaswell talked about with `set_size_inches`. Could also see it as being a little too much "magic" where the user should have to explicitly set the size if they care that much.

**Comment by jasongrout** [comment]
> I have an idea to reconcile both approaches nicely and should also resolve the issue of multiple views with different layouts. Will detail this later. Going AFK for the evening.

@SylvainCorlay - the suspense is killing us :)

In bqplot, we concentrated on letting the user constrain aspect ratios (minimum aspect ratio, maximum aspect ratio), and we set what we thought were reasonable defaults. That let us scale locally, but maintained some control over what the final result looked like. And (IIRC) I think we make the default a fixed size.

**Comment by SylvainCorlay** [comment]
> > I have an idea to reconcile both approaches nicely and should also resolve the issue of multiple views with different layouts. Will detail this later. Going AFK for the evening.
> 
> @SylvainCorlay - the suspense is killing us :)

Doing the write up now.

**Comment by SylvainCorlay** [comment]
About the current situation

- So in jupyter-matplotlib / ipympl, `figure.canvas` is an instance of `DOMWidget`. Sizing and layout of DOMWidget are set by their `layout` attribute, which allow setting any CSS property impacting layout to the top-level DOM element.
- The problem is that if the size is not hard-coded in pixels (or some other constant-size unit), then multiple views of the same figure will have different sizes if displayed in different contexts. This is what happens to bqplot figures currently for example.
- A first issue with that approach is that `figsize` is not the thing setting the layout. Maybe a means to fix this would be to have figsize actually be tied to layout in the case of ipympl somehow.
- The main issue is that for matplotlib, there is only really one figure size in the backend, and the update events when requesting the rendered png for one view is going to impact other views. The pixel ratio also poses an issue in the case of a jupyter notebook / voila dashboard being displayed with two different devices because the requested size takes this into account.

Now, in order for matplotlib to behave consistently with Jupyter widgets and respect the matplotlib API, we need to *align fiction to reality*, in one direction or the other.

 - An approach would be to subclass `ipywidgets.Layout` for the case of the matplotlib figure for it to only accept sizes in inches so that it makes sense for the `figsize` api. In that case, we could easily bind figsize to the layout attribute. A drawback of this approach is that laying out and aligning figures with other jupyter widgets may be very difficult or impossible since the correspondance between inches and other size units depends on the client - and a notebook that works well for one user may look completely different for another.
 - An approach would be for png requests from the backend to attach a view ID so that we can discriminate requests based on it. We would ignore the general rcparam figsize, but forcibly setting the figsize in inches for a figure would take precedence over the layout.

Thoughts?

**Comment by AKuederle** [comment]
Independent of this solution, which resolves the issue with multiple views on to the same figure, I think it would be awesome from a usability perspective to have a button that switches between the actual figure size and the stretched version, which makes full use of the notebook width.

**Comment by kboone** [comment]
As a temporary workaround, here is a way to monkey patch plt.figure to use @thomasaarholt's modified figure() call. Drop this in a cell at the top of your notebook and everything will work as is.

**Comment by allefeld** [comment]
Jupyter newcomer here, my unsolicited opinion:

I don't really mind that the figure adjusts to the width of the notebook window. In data analysis, the more screen space one can give the visualization, the better.

I do however mind that the aspect ratio becomes weird. I would posit that the classic figure aspect ratio is 4:3, going up to 2:1 may make sense, but beyond that it becomes silly (except for special situations).

Is it possible to fix the aspect ratio, so as the figure becomes wider, it also becomes higher?

Or, assuming that the notebook window width corresponds to about 80 em, set the figure height to 60 em?

As I said, newbie here, so maybe what I'm saying doesn't make sense: But why can't the matplotlib figsize simply be used in the notebook? As I understand, it's in inches, converted to pixels through a dpi value, and an html element size can also be specified in inches.

**Comment by djhoese** [comment]
@allefeld I agree and maybe that idea got lost in the conversation. I don't necessarily have a problem with the figure being really large, but with the aspect ratio.

**Comment by thomasaarholt** [comment]
Now, I'm not a developer on this, but I've been following the project for a while and I think I've identified the problem that led me to create this issue. Most of this has been hinted at, but it might be useful to clearly identify the underlying problem:

It seems to me that people (including me) are trying to use `%matplotlib widget` for something that it isn't totally meant for. A lot of people see the **widget backend** as a modern replacement for the **notebook backend**, and as such are disappointed when the widget backend behaves differently.

As I understand it, the widget backend allows people to integrate matplotlib into widget layouts, in which case having a "stretch to fill" is desirable. 

Could one simply implement a switch in the software to set whether the aspect ratio of figures is flexible or fixed?

**Comment by tacaswell** [comment]
Matplotlib figures have a size in inches, however that size is fed back to by the front end (which is definitely desirable.  If you were to embed the figure in a normal GUI then you would expect the figure to shrink / expand to fill the space available.  It is currently possible to resize the widget via styling to have a fixed size in inches (I can't do it off the top of my head), but by default it's behavior is to fill its space.

For @djhoese you should be setting the aspect on your axes to match the aspect of your pixels rather than letting the figure size dictate the aspect ratio of your data (`ax.set_aspect(...)`).

The widget backend is the replacement for the notebook backend (which does not work in modern jupyter due to them very correctly closing a giant security hole we were using to make it work). If you are looking at jupyter in a browser then you _are_ looking at a widget layout.

**Comment by allefeld** [comment]
@thomasaarholt, I understand that `widget` has slightly different focus than `notebook`, but it is the de facto replacement for `notebook`, so it should fulfil that role without too many contortions on the user's side, right?

@tacaswell, alright, so the filling behavior makes sense for a widget embedded in a GUI. Doesn't that mean it should be embedded in a "GUI" within the notebook, too? Meaning, there should be an additional container around it that uses the matplotlib figure size, and then the widget adjusts its size to that of the container? Even better, that container could be manually resizable within the notebook interface (like this text input field is, at least in Chrome).

Again, maybe I'm misunderstanding things.

**Comment by kboone** [comment]
I made a first pass at making this package behave like the `notebook` extension in #147. This commit makes it so that matplotlib controls the figure size rather than the widget attributes. However, this also breaks the traditional widget controls.

I'm not really sure how to make both the matplotlib resizing methods and the widget resizing methods work. I'm getting somewhat used to the codebase now, and I'm willing to help come up with a proper solution.

**Comment by martinRenou** [comment]
As discussed with @tacaswell and @SylvainCorlay during last month's call, it will be difficult to reconcile the widgets resizing logic with the one from Matplotlib.

We did not think at first of any issue with it, we just wanted a responsive widget using Matplotlib, that's the main reason behind the recent behavior changes.

However, Matplotlib is designed for having one client, and the rendering engine obviously needs to know the size of the Canvas in which it renders. While a Jupyter Notebook is supposed to support multiple client pages on the same Notebook at the same time. This makes it an impossible problem because the widget might end up **not** requesting the same size on one page and the other, and it would cause the pages to constantly request resizes of the rendering engine (which lives server-side).

For this reason, I suppose we should simply revert the recent behavior changes on the resize, and stay consistent with other Matplotlib back-ends. I guess @kboone's [PR](https://github.com/matplotlib/jupyter-matplotlib/pull/147) should fix this, thanks a lot!

**Comment by kboone** [comment]
I updated my PR (#147) to keep the widget size and matplotlib figure size in sync. This means that you can now use either the matplotlib interface or the widget interface to resize figures.

This strategy will probably cause some issues if there are multiple clients connecting to the same notebook, but that will require some major backend changes to properly anyway, so I think that it makes sense to turn that into a new issue.

**Comment by kboone** [comment]
I have been using the updated codebase in #147 for a couple weeks now, and it works well for my use cases with both widget sizing and matplotlib sizing.

Are you happy with this implementation, and is there anything else that you would like to see before this gets merged into master?

**Comment by thomasaarholt** [comment]
I am happy, at least :) Will close when it's merged!

**Comment by Jhsmit** [comment]
@kboone when I use the figure monkeypatch to get the old behaviour, I still see differences between the figure in my notebook and what I get if I use ``plt.savefig()``, mostly wrt text; titles, labels etc.

I'm using jupyter a lot to prototype figures and then save then to disk so for me its important that what I see in the notebook is the same as when i save the figure. Is this fixed in this implementation?

**Comment by kboone** [comment]
@Jhsmit That is my workflow as well. I don't see any differences between the jupyter lab figure and the one from savefig() (typically using PDFs or PNGs). I think that what you are seeing is a different issue than the one mentioned in this thread... all that this patch does is keep the size of the figure in sync, it shouldn't have any effect on text rendering. You might want to open a separate issue for what you are seeing.

**Comment by luca-ucsc** [comment]
This was a big (and unwelcome) change, to have the figure stretch and now obey the dpi and 
matplotlib.rcParams['figure.figsize'] = (5.0, 2.5) # For example

What is the solution to get the prior behavior, which made far more sense to me?  Now I get huge figures that use all the space...

**Comment by flutefreak7** [comment]
> @thomasaarholt, I understand that `widget` has slightly different focus than `notebook`, but it is the de facto replacement for `notebook`, so it should fulfil that role without too many contortions on the user's side, right?
> 
> @tacaswell, alright, so the filling behavior makes sense for a widget embedded in a GUI. Doesn't that mean it should be embedded in a "GUI" within the notebook, too? Meaning, there should be an additional container around it that uses the matplotlib figure size, and then the widget adjusts its size to that of the container? Even better, that container could be manually resizable within the notebook interface (like this text input field is, at least in Chrome).
> 
> Again, maybe I'm misunderstanding things.

I think they are saying that the matplotlib canvas is designed to fill it's container in embedding scenarios, like a QT GUI or like JupyterLab. In JupyterLab, when you ask for a figure, matplotlib uses a Jupyter Widget, a DOMWidget subclass, and generates a png image sized to fit into that DOMWidget. The size of the DOMWidget depends on where it's placed. If you aren't doing anything clever then it's placed in the cell output space and expands to fill that space. If you want it to be smaller, you can adjust the size of the widget using the Jupyter widget API (discussed above) which should be similar to adjusting the size of of a Qt window. Unfortunately, neither the Jupyter widget within which the matplotlib canvas is rendered nor the cell output region have a size handle that the user can use to manually change the size the way we are often able to manage window or panel dimensions in a traditional desktop UI.

It sounds like the recent PR makes it cleaner for the jupyter widget to get its size from matplotlib's figure sizing params or for the matplotlib size to be updated when changes are made to the space available to the widget.

Trying to help clarify since I'm not sure your question got answered and your points make a lot of sense.

**Comment by 01baftb** [comment]
I also had the issue of stretched plots when using _%matplotlib widget_. But it was resolved after updating matplotlib to v3.1.3 and ipympl to 0.4.1. 

However, I am still unable to resize the plot as reported here https://github.com/matplotlib/jupyter-matplotlib/issues/74

**Comment by kboone** [comment]
My commits only addressed the stretched plot issue (and went into 0.4.1). Resizing the plot is a separate issue that has not yet been addressed.
